import type {
  AccountDetail,
  AccountUserRow,
  ModuleKpi,
} from "@/types/energy-modules";

export const accountData = {
  companyName: "Vipas Energy Pvt. Ltd.",
  summary:
    "Leading sustainable energy solutions provider specializing in solar, IoT, and smart infrastructure.",
  details: [
    { label: "Company ID", value: "VIPAS-ENERGY-001" },
    { label: "Industry", value: "Renewable Energy" },
    { label: "Website", value: "www.vipasenergy.com" },
    { label: "Email", value: "info@vipasenergy.com" },
    { label: "Phone", value: "+91 80 1234 5678" },
    { label: "Address", value: "Koramangala, Bengaluru, Karnataka 560034" },
  ] satisfies AccountDetail[],
  kpis: [
    {
      id: "users",
      label: "Total Users",
      value: "24",
      unit: "",
      caption: "Active workspace identities",
      trendValue: "3",
      trendLabel: "added this month",
      trendDirection: "up",
      trendSentiment: "positive",
      tone: "green",
      icon: "users",
    },
    {
      id: "roles",
      label: "User Roles",
      value: "5",
      unit: "",
      caption: "Permission groups",
      trendValue: "RBAC",
      trendLabel: "backend-owned",
      trendDirection: "flat",
      trendSentiment: "neutral",
      tone: "blue",
      icon: "shield",
    },
    {
      id: "plan",
      label: "Current Plan",
      value: "Enterprise",
      unit: "",
      caption: "Demo subscription plan",
      trendValue: "Active",
      trendLabel: "annual renewal",
      trendDirection: "up",
      trendSentiment: "positive",
      tone: "violet",
      icon: "credit",
    },
    {
      id: "health",
      label: "Account Health",
      value: "98.7",
      unit: "%",
      caption: "Security and billing health",
      trendValue: "Good",
      trendLabel: "workspace status",
      trendDirection: "up",
      trendSentiment: "positive",
      tone: "green",
      icon: "activity",
    },
  ] satisfies ModuleKpi[],
  billingContacts: [
    { label: "Billing Department", value: "billing@vipasenergy.com" },
    { label: "Finance Team", value: "finance@vipasenergy.com" },
  ] satisfies AccountDetail[],
  planDetails: [
    { label: "Plan", value: "Enterprise Plan" },
    { label: "Renewal Date", value: "Jun 12, 2025" },
    { label: "Billing Cycle", value: "Annual" },
    { label: "Amount", value: "Rs 4,80,000 / year" },
  ] satisfies AccountDetail[],
  users: [
    {
      id: "aditi",
      name: "Aditi Desai",
      email: "aditi.desai@vipasenergy.com",
      role: "Account Admin",
      status: "Active",
      lastActive: "May 18, 2025 2:15 PM",
    },
    {
      id: "rahul",
      name: "Rahul Kapoor",
      email: "rahul.kapoor@vipasenergy.com",
      role: "Operations Manager",
      status: "Active",
      lastActive: "May 18, 2025 11:42 AM",
    },
    {
      id: "neha",
      name: "Neha Patel",
      email: "neha.patel@vipasenergy.com",
      role: "Analyst",
      status: "Active",
      lastActive: "May 18, 2025 10:03 AM",
    },
    {
      id: "meera",
      name: "Meera Joshi",
      email: "meera.joshi@vipasenergy.com",
      role: "Billing Manager",
      status: "Invited",
      lastActive: "-",
    },
  ] satisfies AccountUserRow[],
};
