import type {
  BreakdownItem,
  CarbonComplianceReport,
  CarbonInitiative,
  CarbonSiteRow,
  CarbonSiteTotals,
  ModuleKpi,
  TrendSeries,
} from "@/types/energy-modules";

export const carbonData = {
  refreshedLabel: "Emissions rollups refreshed 5 mins ago",
  timezoneLabel: "Sustainability metrics staged from approved reporting tables",
  kpis: [
    {
      id: "total-emissions",
      label: "Total Emissions",
      value: "12,845",
      unit: "tCO2e",
      caption: "Portfolio emissions this period",
      trendValue: "3.2%",
      trendLabel: "vs May 5 - May 11",
      trendDirection: "up",
      trendSentiment: "negative",
      tone: "green",
      icon: "cloud",
    },
    {
      id: "intensity",
      label: "Emission Intensity",
      value: "0.42",
      unit: "tCO2e/MWh",
      caption: "Normalized demand intensity",
      trendValue: "4.6%",
      trendLabel: "improvement",
      trendDirection: "down",
      trendSentiment: "positive",
      tone: "green",
      icon: "leaf",
    },
    {
      id: "reduction",
      label: "Reduction vs Last Period",
      value: "-412",
      unit: "tCO2e",
      caption: "Avoided emissions from initiatives",
      trendValue: "8.1%",
      trendLabel: "improvement",
      trendDirection: "down",
      trendSentiment: "positive",
      tone: "blue",
      icon: "activity",
    },
    {
      id: "target",
      label: "Progress to Target",
      value: "68",
      unit: "%",
      caption: "Target: 18,500 tCO2e by Dec 31",
      trendValue: "On track",
      trendLabel: "annual target",
      trendDirection: "up",
      trendSentiment: "positive",
      tone: "violet",
      icon: "target",
    },
  ] satisfies ModuleKpi[],
  trendLabels: [
    "May 12",
    "May 13",
    "May 14",
    "May 15",
    "May 16",
    "May 17",
    "May 18",
  ],
  trendSeries: [
    {
      name: "Total Emissions",
      values: [860, 1580, 900, 1390, 940, 1870, 1220],
      tone: "primary",
      area: true,
    },
    {
      name: "Emission Intensity",
      values: [0.38, 0.48, 0.34, 0.42, 0.52, 0.41, 0.45],
      tone: "info",
      dashed: true,
    },
    {
      name: "Previous Period",
      values: [520, 860, 480, 740, 530, 990, 640],
      tone: "neutral",
    },
  ] satisfies TrendSeries[],
  breakdown: [
    {
      name: "Grid Electricity",
      value: 6102,
      label: "6,102 tCO2e",
      percentage: 47.5,
    },
    {
      name: "Natural Gas",
      value: 3248,
      label: "3,248 tCO2e",
      percentage: 25.3,
    },
    { name: "Diesel", value: 1689, label: "1,689 tCO2e", percentage: 13.2 },
    {
      name: "Solar On-site",
      value: 1024,
      label: "1,024 tCO2e",
      percentage: 8.0,
    },
    { name: "Other Fuels", value: 782, label: "782 tCO2e", percentage: 6.0 },
  ] satisfies BreakdownItem[],
  initiatives: [
    {
      id: "solar-expansion-phase-2",
      title: "Solar Expansion - Phase 2",
      annualImpactTco2e: 1200,
      progressPercent: 75,
      status: "On Track",
    },
    {
      id: "hvac-efficiency-upgrade",
      title: "HVAC Efficiency Upgrade",
      annualImpactTco2e: 450,
      progressPercent: 40,
      status: "In Progress",
    },
    {
      id: "fleet-electrification",
      title: "Fleet Electrification",
      annualImpactTco2e: 300,
      progressPercent: 15,
      status: "Planned",
    },
    {
      id: "led-lighting-retrofit",
      title: "LED Lighting Retrofit",
      annualImpactTco2e: 120,
      progressPercent: 90,
      status: "Completed",
    },
  ] satisfies CarbonInitiative[],
  reports: [
    {
      id: "sustainability-report-q1-2025",
      title: "Sustainability Report (Q1 2025)",
      detail: "Generated on Apr 15, 2025",
    },
    {
      id: "ghg-inventory-fy-2024",
      title: "GHG Inventory (FY 2024)",
      detail: "Generated on Jan 20, 2025",
    },
    {
      id: "iso-14064-summary",
      title: "ISO 14064-1 Summary",
      detail: "Last updated on Mar 28, 2025",
    },
  ] satisfies CarbonComplianceReport[],
  rows: [
    {
      id: "solar-alpha",
      site: "Solar Park Alpha",
      emissions: 4102,
      intensity: 0.38,
      deltaPercent: -6.2,
    },
    {
      id: "wind-beta",
      site: "Wind Farm Beta",
      emissions: 2845,
      intensity: 0.45,
      deltaPercent: -3.1,
    },
    {
      id: "manufacturing",
      site: "Manufacturing Plant",
      emissions: 2310,
      intensity: 0.52,
      deltaPercent: 1.4,
    },
    {
      id: "data-center",
      site: "Data Center 1",
      emissions: 1642,
      intensity: 0.41,
      deltaPercent: -2.7,
    },
    {
      id: "logistics",
      site: "Logistics Hub",
      emissions: 1126,
      intensity: 0.36,
      deltaPercent: -5.5,
    },
    {
      id: "corporate-office",
      site: "Corporate Office",
      emissions: 820,
      intensity: 0.29,
      deltaPercent: -1.9,
    },
  ] satisfies CarbonSiteRow[],
  siteTotals: {
    emissions: 12845,
    intensity: 0.42,
    deltaPercent: -3.2,
  } satisfies CarbonSiteTotals,
};
