import type {
  ActionAlert,
  BarComparisonItem,
  ModuleKpi,
  RatePlanRow,
  TrendSeries,
} from "@/types/energy-modules";

export const rateTariffData = {
  refreshedLabel: "Rate tables refreshed 5 mins ago",
  timezoneLabel: "Tariff effective dates normalized to workspace currency",
  kpis: [
    {
      id: "weighted-rate",
      label: "Weighted Avg. Rate",
      value: "9.42",
      unit: "Rs/kWh",
      caption: "Blended rate across active plans",
      trendValue: "2.1%",
      trendLabel: "below current baseline",
      trendDirection: "down",
      trendSentiment: "positive",
      tone: "green",
      icon: "wallet",
    },
    {
      id: "active-tariffs",
      label: "Active Tariff Plans",
      value: "18",
      unit: "",
      caption: "Plans available for comparison",
      trendValue: "2",
      trendLabel: "added this week",
      trendDirection: "up",
      trendSentiment: "positive",
      tone: "blue",
      icon: "database",
    },
    {
      id: "monthly-cost",
      label: "Estimated Monthly Cost",
      value: "742K",
      unit: "Rs",
      caption: "Modeled consumption cost",
      trendValue: "6.4%",
      trendLabel: "vs last period",
      trendDirection: "up",
      trendSentiment: "neutral",
      tone: "violet",
      icon: "credit",
    },
    {
      id: "savings",
      label: "Savings Opportunity",
      value: "52.7K",
      unit: "Rs",
      caption: "Identified through rate comparison",
      trendValue: "6.6%",
      trendLabel: "potential reduction",
      trendDirection: "down",
      trendSentiment: "positive",
      tone: "green",
      icon: "target",
    },
  ] satisfies ModuleKpi[],
  trendLabels: [
    "May 12",
    "May 13",
    "May 14",
    "May 15",
    "May 16",
    "May 17",
    "May 18",
  ],
  trendSeries: [
    {
      name: "All Rates",
      values: [8.8, 8.2, 9.6, 12.1, 14.6, 7.8, 10.4],
      tone: "primary",
      area: true,
    },
    {
      name: "Fixed Rates",
      values: [10.1, 9.4, 9.8, 9.9, 11.2, 8.0, 9.2],
      tone: "info",
      dashed: true,
    },
    {
      name: "Variable Rates",
      values: [6.2, 5.4, 6.8, 6.3, 8.4, 5.1, 6.0],
      tone: "accent",
      dashed: true,
    },
  ] satisfies TrendSeries[],
  comparison: [
    { label: "State Utility", value: 9.85 },
    { label: "Vipas Fixed", value: 8.75 },
    { label: "PowerGrid", value: 10.4 },
    { label: "Flexi", value: 7.2 },
    { label: "Industrial", value: 9.1 },
  ] satisfies BarComparisonItem[],
  alerts: [
    {
      id: "rate-revision",
      title: "Peak Advantage plan revision",
      description: "Rate change effective May 26, 2025.",
      meta: "Rate change",
      severity: "Medium",
    },
    {
      id: "contract-expiry",
      title: "Green Saver contract nearing renewal",
      description: "Expires in 28 days and should be compared.",
      meta: "Expiring soon",
      severity: "Medium",
    },
    {
      id: "rate-db",
      title: "Vipas Rate DB opportunity",
      description: "Neighboring region rate data suggests a better TOU plan.",
      meta: "Subscription feature",
      severity: "Info",
    },
  ] satisfies ActionAlert[],
  rows: [
    {
      id: "cni-tou",
      plan: "C&I Time of Use Plan",
      provider: "State Utility",
      region: "Karnataka",
      rateType: "TOU",
      unitRate: 9.85,
      status: "Active",
    },
    {
      id: "green-fixed",
      plan: "Green Saver Fixed Plan",
      provider: "Vipas Energy",
      region: "Tamil Nadu",
      rateType: "Fixed",
      unitRate: 8.75,
      status: "Active",
    },
    {
      id: "flexi-variable",
      plan: "Flexi Power Variable Plan",
      provider: "State Utility",
      region: "Maharashtra",
      rateType: "Variable",
      unitRate: 7.2,
      status: "Watch",
    },
    {
      id: "peak-advantage",
      plan: "Peak Advantage Plan",
      provider: "PowerGrid Corp",
      region: "Telangana",
      rateType: "TOU",
      unitRate: 10.4,
      status: "Open",
    },
  ] satisfies RatePlanRow[],
};
