import type { ConnectorCard, ModuleKpi } from "@/types/energy-modules";

export const subscriptionsData = {
  kpis: [
    {
      id: "enabled-modules",
      label: "Enabled Modules",
      value: "4",
      unit: "modules",
      caption: "Demand, supply, rates, and carbon",
      trendValue: "AI",
      trendLabel: "assistant visible",
      trendDirection: "up",
      trendSentiment: "positive",
      tone: "green",
      icon: "database",
    },
    {
      id: "connected-services",
      label: "Connected Services",
      value: "7",
      unit: "connectors",
      caption: "Visual-only connector inventory",
      trendValue: "5",
      trendLabel: "active integrations",
      trendDirection: "up",
      trendSentiment: "positive",
      tone: "blue",
      icon: "cloud",
    },
    {
      id: "rate-db",
      label: "Vipas Rate DB",
      value: "Enabled",
      unit: "",
      caption: "Subscription-gated tariff intelligence",
      trendValue: "Ready",
      trendLabel: "for rate story",
      trendDirection: "up",
      trendSentiment: "positive",
      tone: "violet",
      icon: "wallet",
    },
    {
      id: "usage",
      label: "Workspace Usage",
      value: "72",
      unit: "%",
      caption: "Seats and API call allocation",
      trendValue: "Stable",
      trendLabel: "current plan",
      trendDirection: "flat",
      trendSentiment: "neutral",
      tone: "green",
      icon: "users",
    },
  ] satisfies ModuleKpi[],
  enabledModules: [
    "Demand Management",
    "Supply Management",
    "Rate & Tariff",
    "Carbon Management",
    "Vipas Assistant",
  ],
  connectors: [
    {
      id: "google-workspace",
      name: "Google Workspace",
      description: "Docs and report package export workspace.",
      status: "Connected",
      category: "Productivity",
    },
    {
      id: "microsoft-365",
      name: "Microsoft 365",
      description: "Office documents, calendar, and stakeholder delivery.",
      status: "Connected",
      category: "Productivity",
    },
    {
      id: "slack",
      name: "Slack",
      description: "Alert routing and operational notifications.",
      status: "Connected",
      category: "Messaging",
    },
    {
      id: "aws-s3",
      name: "AWS S3",
      description: "Document, extract, and report file storage.",
      status: "Connected",
      category: "Storage",
    },
    {
      id: "vipas-rate-db",
      name: "Vipas Rate DB",
      description: "Rate and tariff comparison intelligence.",
      status: "Enabled",
      category: "Data Product",
    },
    {
      id: "accuweather",
      name: "AccuWeather",
      description: "Approved public weather source for demand context.",
      status: "Open",
      category: "Public Source",
    },
  ] satisfies ConnectorCard[],
};
