import type { DemandDashboardData } from "@/types/demand";

export const demandDashboardData = {
  dateRangeLabel: "May 12 - May 18, 2025",
  refreshedLabel: "Data refreshed 5 mins ago",
  timezoneLabel: "All times shown in Asia/Kolkata (IST)",
  kpis: [
    {
      id: "total-demand",
      label: "Total Demand",
      value: "128.4",
      unit: "MWh",
      caption: "Enterprise portfolio demand",
      trend: {
        direction: "up",
        value: "6.7%",
        label: "vs May 5 - May 11",
        sentiment: "positive",
      },
      icon: "zap",
      tone: "green",
    },
    {
      id: "average-daily-demand",
      label: "Average Daily Demand",
      value: "18.3",
      unit: "MWh",
      caption: "Daily normalized usage",
      trend: {
        direction: "up",
        value: "4.3%",
        label: "vs May 5 - May 11",
        sentiment: "positive",
      },
      icon: "bars",
      tone: "green",
    },
    {
      id: "peak-demand",
      label: "Peak Demand",
      value: "28.7",
      unit: "MWh",
      caption: "May 16, 2025 - 2:30 PM",
      trend: {
        direction: "up",
        value: "Spike captured",
        label: "assistant-ready insight",
        sentiment: "neutral",
      },
      icon: "activity",
      tone: "blue",
    },
    {
      id: "forecast-variance",
      label: "Forecast Variance",
      value: "-2.4",
      unit: "%",
      caption: "Forecast model variance",
      trend: {
        direction: "down",
        value: "-2.4%",
        label: "vs forecast",
        sentiment: "positive",
      },
      icon: "target",
      tone: "violet",
    },
  ],
  trend: [
    {
      label: "May 12",
      actual: 12.2,
      forecast: 13.1,
      previous: 9.7,
      isForecast: false,
    },
    {
      label: "May 12 PM",
      actual: 23.4,
      forecast: 21.9,
      previous: 14.1,
      isForecast: false,
    },
    {
      label: "May 13",
      actual: 17.8,
      forecast: 19.3,
      previous: 8.2,
      isForecast: false,
    },
    {
      label: "May 13 PM",
      actual: 24.6,
      forecast: 23.1,
      previous: 15.8,
      isForecast: false,
    },
    {
      label: "May 14",
      actual: 15.3,
      forecast: 17.2,
      previous: 10.4,
      isForecast: false,
    },
    {
      label: "May 14 PM",
      actual: 22.5,
      forecast: 21.4,
      previous: 19.1,
      isForecast: false,
    },
    {
      label: "May 15",
      actual: 16.1,
      forecast: 18.0,
      previous: 11.8,
      isForecast: false,
    },
    {
      label: "May 15 PM",
      actual: 26.7,
      forecast: 24.2,
      previous: 20.7,
      isForecast: false,
    },
    {
      label: "May 16",
      actual: 18.9,
      forecast: 17.6,
      previous: 13.9,
      isForecast: false,
    },
    {
      label: "May 16 PM",
      actual: 28.7,
      forecast: 22.4,
      previous: 17.5,
      isForecast: false,
    },
    {
      label: "May 17",
      actual: 20.4,
      forecast: 21.2,
      previous: 15.8,
      isForecast: false,
    },
    {
      label: "May 17 PM",
      actual: 31.2,
      forecast: 24.7,
      previous: 23.2,
      isForecast: false,
    },
    {
      label: "May 18",
      actual: 18.4,
      forecast: 23.5,
      previous: 16.9,
      isForecast: true,
    },
    {
      label: "May 18 PM",
      actual: 14.6,
      forecast: 20.2,
      previous: 12.1,
      isForecast: true,
    },
  ],
  siteBreakdown: [
    {
      name: "Solar Park Alpha",
      demandMwh: 34.5,
      percentage: 26.9,
    },
    {
      name: "Wind Farm Beta",
      demandMwh: 28.7,
      percentage: 22.4,
    },
    {
      name: "Manufacturing Plant",
      demandMwh: 22.1,
      percentage: 17.2,
    },
    {
      name: "Data Center 1",
      demandMwh: 18.6,
      percentage: 14.5,
    },
    {
      name: "Other Sites",
      demandMwh: 24.5,
      percentage: 19.0,
    },
  ],
  alerts: [
    {
      id: "solar-park-spike",
      title: "High demand detected at Solar Park Alpha",
      timestamp: "May 16, 2025 - 2:30 PM",
      severity: "High",
      description: "Cooling load and industrial activity exceeded forecast.",
    },
    {
      id: "wind-forecast-gap",
      title: "Usage 18% above forecast at Wind Farm Beta",
      timestamp: "May 16, 2025 - 1:15 PM",
      severity: "Medium",
      description: "Assistant can compare supply plan impact.",
    },
    {
      id: "night-consumption",
      title: "Unusual nighttime consumption at Data Center 1",
      timestamp: "May 16, 2025 - 12:45 AM",
      severity: "Low",
      description: "Potential schedule drift detected in staged data.",
    },
  ],
  topSites: [
    {
      id: "solar-park-alpha",
      site: "Solar Park Alpha",
      totalDemandMwh: 34.5,
      percentageOfTotal: 26.9,
      deltaPercent: 8.4,
      status: "High",
    },
    {
      id: "wind-farm-beta",
      site: "Wind Farm Beta",
      totalDemandMwh: 28.7,
      percentageOfTotal: 22.4,
      deltaPercent: 3.1,
      status: "Normal",
    },
    {
      id: "manufacturing-plant",
      site: "Manufacturing Plant",
      totalDemandMwh: 22.1,
      percentageOfTotal: 17.2,
      deltaPercent: 1.2,
      status: "Normal",
    },
    {
      id: "data-center-1",
      site: "Data Center 1",
      totalDemandMwh: 18.6,
      percentageOfTotal: 14.5,
      deltaPercent: 5.7,
      status: "Watch",
    },
    {
      id: "logistics-hub",
      site: "Logistics Hub",
      totalDemandMwh: 12.3,
      percentageOfTotal: 9.6,
      deltaPercent: -2.1,
      status: "Normal",
    },
  ],
  assistantPrompts: [
    {
      id: "demand-spike",
      label: "What drove the May 16 demand spike?",
    },
    {
      id: "forecast-variance",
      label: "Show forecast vs actual demand for this week.",
    },
    {
      id: "site-risk",
      label: "Which sites need attention before the next billing cycle?",
    },
  ],
} satisfies DemandDashboardData;
